### ISSUE TITLE
Capitalisation error on weather info

### ISSUE THREAD

**Issue by brandonskerritt** [JahanUoL/MEAN-weather-app#18]
Really cool UI, love the gifs!

Right now in Liverpool:
```
Liverpool, GB
2020-05-23, 15:33:25

**broken clouds**

Feels like: 6.01°C

Humidty: 42%

Wind speed: 12.9mph, ← W

Sunrise at: 04:59:43, sunset at: 21:18:00
```

`broken clouds` is not capitalised correctly :)

**Comment by JahanUoL** [comment]
Hey man! Thanks for the feedback, glad you could check it out! I think the API gave the data like that, but will be doing some further UI improvements soon!:)
